version: '2'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - website-monitor
  postgres:
      image: postgres:9.4
      environment: 
          - POSTGRES_USER=demo
          - POSTGRES_PASSWORD=demo
          - POSTGRES_DB=demo
      ports:
          - 5432:5432
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - website-monitor
  # producer:
  #   build: .
  #   networks:
  #     - website-monitor
networks:
  website-monitor:
    driver: bridge
